<?php

// this is sample config, plz save as "config.inc" and change everything you need to change
defined('DB_HOST') or define("DB_HOST", "localhost");
defined('DB_USER') or define("DB_USER", "root");
defined('DB_PASS') or define("DB_PASS", "");
defined('DB_NAME') or define("DB_NAME", "development_data_process");


defined('INCLUDE_PATH') or define('INCLUDE_PATH', 'C:/xampp/htdocs/uchoice/global_config/development_data_process');

// error_reporting(0);

?>
